version: '3.7'

services:
  linkslpp:
    image: muriloda/lpplinks:1.0
    container_name: linkslpp
    build:
      context: .
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      DBHOST: links_db
      DBUSERNAME: lpp
      DBPASSWORD: senha1234
      DBDATABASE: links
    ports:
      - '1234:8080'
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
    depends_on:
      - links_db
    restart: unless-stopped
  links_db:
    container_name: links_db
    image: postgres:latest
    environment: 
      POSTGRES_DB: links
      POSTGRES_PASSWORD: senha1234
      POSTGRES_USER: lpp
    restart: unless-stopped
